curriculum = {
    '6e': [
        "Les domaines d’application de l’informatique", "Le matériel de l’ordinateur", "Les logiciels",
        "Les attitudes citoyennes face aux contenus et outils informatiques", "Mise en marche de l’ordinateur",
        "Supports de sauvegarde", "Recherche du plus court chemin", "Ordonnancement des tâches",
        "Le clavier et la souris", "Utilisation d’un logiciel de productivité", "Navigateurs", "Moteur de recherche",
        "Classification des périphériques", "Les types de supports de sauvegarde", "Entretien du matériel informatique",
        "Équipements de protection", "Notion de système d’exploitation", "Éléments graphiques d’un SE",
        "Opération sur un logiciel", "Notion de configuration", "Fichiers et dossiers",
        "Initiation au traitement de texte", "Mise en forme et impression d’un document texte",
        "Messagerie électronique"
    ],
    '5e': [
        "Gestion du compte utilisateur", "Environnement de travail d’un système d’exploitation",
        "Les caractéristiques d’un ordinateur", "Entretien de l’ordinateur", "Organisation des données",
        "Rechercher le plus court chemin", "Notion d’ordonnancement", "Généralités sur le traitement de texte",
        "Création d’un document texte", "Mise en forme de document texte", "Impression d’un document texte",
        "Généralités sur internet", "Accès à internet", "Présentation des navigateurs", "Naviguer sur internet",
        "Présentation des moteurs de recherche", "Effectuer une recherche",
        "Ouverture et création d’un compte de messagerie", "Utilisation de la messagerie électronique",
        "L’inscription à une communauté virtuelle"
    ],
    '4e': [
        "Généralités sur les réseaux", "Topologies et Architectures des réseaux", "Les équipements réseaux",
        "Configuration d’un ordinateur sur le réseau", "Connexion d’un ordinateur sur le réseau",
        "Généralités sur internet", "La Navigation sur internet", "Recherche de l’information sur internet",
        "Récupération d’une ressource sur intérêt", "Messagerie électronique",
        "Généralités sur le système d’exploitation", "Éléments graphiques d’un système d’exploitation",
        "Démarrage et configuration d’un ordinateur", "Nettoyage d’un ordinateur et conservation des supports",
        "Entretien logiciel d’un ordinateur", "Gestion de fichiers et dossiers",
        "Insertion des objets dans un document texte", "Utilisation de style et correction du document",
        "Réalisation d’un publipostage", "Production automatique d’une table des matières",
        "Introduction aux tableurs", "Gestion d’une feuille de calcul", "Operations simples dans un tableur",
        "Mise en page et impression des données d’un tableur", "Création d’un diaporama simple",
        "Introduction à l’algorithme", "Les instructions simples", "Exécution d’un algorithme"
    ],
    '3e': [
        "Description des périphériques d’un ordinateur", "Interconnexion des éléments de base d’un ordinateur",
        "Les types de mémoires d’un ordinateur", "Les systèmes d’exploitation", "Les logiciels d’applications",
        "La notion de maintenance", "Les mesures de protection du matériel et du logiciel", "Gestion des logiciels",
        "Optimisation des performances d’un ordinateur", "Notion de fichier", "Rappels sur les tableurs",
        "Les formules simples", "Les fonctions de texte", "Les fonctions de DATE et HEURE",
        "Les fonctions mathématiques", "Les mises en forme conditionnelles", "Insertion des graphiques",
        "Introduction aux systèmes de numération", "Conversion d’une base à une autre", "Arithmétique binaire",
        "La notion d’information", "Coder une information", "Les unités de mesures des données",
        "Les unités de mesures du matériel", "Généralités sur les algorithmes", "Les instructions simples",
        "Les structures algorithmiques", "Construction d’un organigramme"
    ],
    '2nde': [
        "Les ports d’un ordinateur", "Les caractéristiques matérielles d’un PC", "Les logiciels",
        "Notion de fichier", "Les tâches d’entretien des supports de stockage", "Maintenance des supports de stockage",
        "Outillage de la carte mère", "Généralités sur le PréAO", "Production d’un document de présentation",
        "Généralités sur les texteurs", "Utilisation d’un logiciel de traitement de texte",
        "Insérer les formules scientifiques dans Word", "Notion de tableur",
        "Les formules et fonctions dans un tableur", "Résolution d’un système d’équation",
        "Généralités sur l’infographie", "Identifier les fichiers multimédias", "Montage audio/vidéo",
        "Recherche et correspondance sur internet", "Usages des réseaux sociaux",
        "Notion de groupe sur les réseaux sociaux : cas de WhatsApp", "Notions de base algorithmique",
        "Écriture et exécution d’un algorithme", "Les structures de contrôle",
        "Traduire un algorithme en langage C", "Notion de page web", "Les balises HTML",
        "Exécution d’un code HTML", "Présentation d’un PC", "L’unité centrale", "Mise en page d’un document",
        "Produire une feuille de calculs"
    ],
    '1e': [
        "Installation d’un SE", "Les opérations post-installation d’un SE", "Introduction à l’invite de commandes",
        "Utilisation de l’invite de commandes", "Introduction à la sécurité informatique",
        "Utiliser les fichiers multimédias", "Introduction aux systèmes d’information",
        "Méthodes d’analyse et de conception des systèmes d’information", "Généralités sur les bases de données",
        "Les caractéristiques d’une table", "Les fonctions d’une base de données", "Les structures itératives",
        "Les structures conditionnelles", "Généralités sur les structures de données", "Les tableaux",
        "Notions de procédure et fonction", "Insérer les fichiers multimédias dans une page web",
        "Insérer des tableaux et formulaires en HTML", "Organiser les dossiers du site et mise en place du CSS",
        "Introduction au JavaScript", "Notions de base du JavaScript", "Structures de contrôles, tableaux et fonctions en JavaScript",
        "Les événements en JavaScript", "Introduction au langage C", "Les structures de contrôle en C",
        "Les tableaux en C", "Les sous-programmes en C", "Exécution d’un programme C",
        "Optimiser un environnement de travail", "Les concepts généraux de la sécurité informatique",
        "Quelques actions de la sécurité informatique", "Étude d’un logiciel de préAO : Cas de MS PowerPoint",
        "Rappels des généralités sur les tableurs", "Utilisation des formules et fonctions prédéfinies dans un tableur",
        "Insertion des graphiques et impression d’une feuille de calcul", "Les structures de contrôle",
        "Les organigrammes", "Généralités sur le HTML", "Mise en forme en HTML",
        "Insertion des liens, images, sons et vidéos en HTML", "Présentation des outils d’un logiciel d’infographie : Adobe Photoshop",
        "Création et administration d’un groupe dans un réseau social", "Généralités sur le cloud computing",
        "Généralités sur la virtualisation"
    ],
    'Tle': [
        "Systèmes informatiques", "Exploitation d’un environnement numérique", "Description des types des systèmes informatiques",
        "Description de l’architecture logicielle d’un système informatique",
        "Description de l’architecture matérielle d’un système informatique", "Protection matérielle et logicielle",
        "Gestion des fluctuations de l’énergie électrique", "Création de contenus numériques",
        "Généralités sur les tableurs", "Utilisation d’une feuille de calcul", "Réseaux informatiques",
        "Topologie et architectures réseaux", "Les équipements réseaux", "Les protocoles réseaux",
        "L’adressage réseau", "Créer et configurer un réseau informatique de 03 PC",
        "Commandes réseaux et simulation d’un réseau", "Systèmes d’information et bases de données",
        "Généralités sur les SI", "Élaboration d’un MCD", "Passage du MCD au MLD", "Bases de données",
        "Les SGBD et fonctions de manipulations des données dans une BD",
        "Requêtes SQL de définition et de manipulation des données",
        "Implémentation d’une base de donnée dans MS Access", "Algorithmique et programmation",
        "Recherche séquentielle dans un tableau", "Recherche du maximum/minimum dans un tableau",
        "Programmation en C", "Structures de contrôle en langage C", "Utiliser les tableaux en C",
        "Traduire un algorithme de recherche séquentielle en C", "Identifier/interpréter/corriger les erreurs",
        "Composants matériels", "Composants logiciels", "Dysfonctionnement d’un environnement de travail",
        "Services de communication électronique", "Sauvegarde et partage des ressources numériques",
        "Les notions d’intranet, extranet et internet", "Les composants d’un SI", "Fonctions d’un SI",
        "Production d’une feuille de calculs", "Utilisation des fonctions et zone d’impression",
        "Reproduction de documents : facture, bulletin", "Traitement de texte : mise en forme avancée",
        "Insertion d’objets dans un texte"
    ]
}